# Generated by Django 4.1.5 on 2023-01-12 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(editable=False, verbose_name='User ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('image_id', models.UUIDField(blank=True, null=True, verbose_name='Image ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.color', verbose_name='Color')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.item', verbose_name='Item')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.place', verbose_name='Place')),
            ],
            options={
                'verbose_name_plural': 'Lost Posts',
            },
        ),
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(editable=False, verbose_name='User ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('image_id', models.UUIDField(blank=True, null=True, verbose_name='Image ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.color', verbose_name='Color')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.item', verbose_name='Item')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.place', verbose_name='Place')),
            ],
            options={
                'verbose_name_plural': 'Found Posts',
            },
        ),
    ]
