# Generated by Django 4.1 on 2023-01-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_found_uid_alter_lost_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='image_id',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Image ID'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='image_id',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Image ID'),
        ),
    ]
