version: '3.8'
services:
  api:
    build: .
    networks:
      - in-net
    volumes:
      - type: volume
        source: code-vol
        target: /code
    ports:
      - "8000:8000"
    container_name: $HOST
    command: 'gunicorn core.wsgi:application --bind :8000 --workers 4'
    env_file:
      - .env
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    networks:
      - in-net
    volumes:
      - type: volume
        source: db-vol
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: $DB_HOST

networks:
  in-net:
    name: in-net
    internal: true

volumes:
  code-vol:
    name: auth-code-vol
  db-vol:
    name: auth-db-vol