
version: '3.8'
services:
  api:
    build: .
    networks:
      - in-net
    volumes:
      - .:/code
    ports:
      - "$SVC_PORT:$SVC_PORT"
    container_name: $HOST
    command: sh -c "chmod +x /code/migrate.sh && sh /code/migrate.sh && /code/entrypoint.sh"
    env_file:
      - .env
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    restart: always
    networks:
      - in-net
    volumes:
      - type: volume
        source: db-vol
        target: /var/lib/postgresql/data
    container_name: $DB_HOST
    environment:
      - POSTGRES_DB=$DB
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD

networks:
  in-net:
    name: in-net
    internal: true

volumes:
  db-vol:
    name: auth-db-vol
