
version: '3.8'
services:
  api:
    build: .
    networks:
      - in-net
      - gateway-in-net
    volumes:
      - .:/code
    ports:
      - "$SVC_PORT:$SVC_PORT"
    container_name: $HOST
    command: $CMD
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    networks:
      - in-net
    volumes:
      - type: volume
        source: db-vol
        target: /var/lib/postgresql/data
    container_name: $DB_HOST
    environment:
      - POSTGRES_DB=$DB
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD

networks:
  in-net:
    name: post-in-net               #internal net between api and db (svc in net)
    internal: true
  gateway-in-net:
    name: gateway-in-net            #internal net between api and gateway
    internal: true

volumes:
  db-vol:
    name: post-db-vol
