version: '3.8'
services:
  api:
    build: .
    networks:
      - gateway-in-net
      - ex-net
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    container_name: web-gateway-api
    command: 'gunicorn app:app --bind :5000 --workers 4'
    env_file:
      - .env

networks:
  gateway-in-net:
    name: gateway-in-net
    internal: true
  ex-net:
    name: ex-net

