version: '3.8'
services:
  api:
    build: .
    networks:
      - in-net
      - ex-net
    volumes:
      - type: volume
        source: code-vol
        target: /code
    ports:
      - "5000:5000"
    container_name: gateway-api
    command: 'gunicorn app:app --bind :5000 --workers 3'
    env_file:
      - .env

networks:
  in-net:
    name: in-net
    internal: true
  ex-net:
    name: ex-net

volumes:
  code-vol:
    name: gw-code-vol
